### PR TITLE
Updating schedule to run every 10 minutes weekdays

### PR DESCRIPTION
**Pull request by cadedaniel**
Signed-off-by: Cade Daniel <edacih@gmail.com>

Not sure what timezone it's in, will check

### CODE REVIEW

**Comment by cadedaniel** [comment]
I think this will double-trigger on common multiples of 30 and 10, need to fix

**Comment by simon-mo** [comment]
https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#schedule

You need to change the hours to UTC here... 

> You can schedule a workflow to run at specific UTC times using [POSIX cron syntax](https://pubs.opengroup.org/onlinepubs/9699919799/utilities/crontab.html#tag_20_25_07). Scheduled workflows run on the latest commit on the default or base branch. The shortest interval you can run scheduled workflows is once every 5 minutes.

**Comment by cadedaniel** [comment]
Okay, now it's every 10 minutes on weekdays, 30 mins on weekends.

**Comment by cadedaniel** [comment]
@simon-mo ready for review

**Review by simon-mo — APPROVED** [review]

**Pull request merged**
